# Generated by Django 5.2.1 on 2025-07-01 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0003_alter_workspacemember_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workspacemember',
            old_name='created_at',
            new_name='joined_at',
        ),
        migrations.AddField(
            model_name='workspacemember',
            name='permission',
            field=models.CharField(choices=[('view', 'View'), ('edit', 'Edit')], default='view', max_length=10),
        ),
    ]
