# Generated by Django 5.2.1 on 2025-05-21 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_comment_noteshare'),
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='group_id',
        ),
        migrations.AddField(
            model_name='note',
            name='workspace',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workspaces.workspace'),
        ),
    ]
