# Generated by Django 5.2.1 on 2025-06-19 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_remove_note_group_id_note_workspace'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='parentComment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='notes.comment'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='note',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='notes.note'),
        ),
    ]
