# Generated by Django 5.2.1 on 2025-06-22 19:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_note_is_shared_via_link_note_link_permission_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='share_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
