# Generated by Django 5.2.1 on 2025-06-27 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_alter_note_share_token_delete_comment'),
        ('workspaces', '0002_workspace_thumbnail_alter_workspacemember_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workspaces.workspace'),
        ),
    ]
